Pullrequest
MKhlon/bookstore pull request #1
Opened 2023-02-10 20:18 UTC by MKhlon

2023-02-13 09:11 UTC, oleksandr-fomenko requested changes

2023-02-13 09:11 UTC, oleksandr-fomenko commented on pom.xml
> +            <version>2.0.0</version>
Optional comment: keep versions of the dependencies in the properties section

2023-02-13 09:11 UTC, oleksandr-fomenko commented on src/test/java/com/bookstore/utils/Utils.java
> +@Data
data annotation doesn't make any sense here

2023-02-13 09:11 UTC, oleksandr-fomenko commented on src/test/java/com/bookstore/utils/Utils.java
> +public class Utils {
Better to rename it to TestDataUtils

2023-02-13 09:11 UTC, oleksandr-fomenko commented on src/test/java/com/bookstore/utils/Utils.java
> +public class Utils {
and add a private constructor + make class final

2023-02-13 09:11 UTC, oleksandr-fomenko commented on src/test/java/com/bookstore/utils/Messages.java
> +public class Messages {
it's a good practice to add private constructors to such kind of classes and make class final

2023-02-13 09:11 UTC, oleksandr-fomenko commented on src/main/java/com/bookstore/model/Booking.java
> +    @JsonFormat(pattern = "HH:mm:ss.SSSSSSSSS")
In the classic MVC architecture data model != domain model. You need to have separate models for the DB layer and API layers and map them to each other.

2023-02-13 09:11 UTC, oleksandr-fomenko commented on src/main/java/com/bookstore/controller/BookingController.java
> +                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
FYI, not comment: it's a good practice to declare and throw custom exceptions for such cases and handle the using Spring ExceptionHandlers - https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc

2023-02-13 09:20 UTC, oleksandr-fomenko commented
it's better to have a separate configuration application.yml for the application testing. Place it under src/test/resources, use h2DB instead of real DB

2023-02-13 10:04 UTC, MKhlon commented on pom.xml
> +            <version>2.0.0</version>
done

2023-02-13 10:05 UTC, MKhlon commented on src/test/java/com/bookstore/utils/Utils.java
> +@Data
fixed

2023-02-13 10:08 UTC, MKhlon commented on src/test/java/com/bookstore/utils/Utils.java
> +public class Utils {
fixed

2023-02-13 10:13 UTC, MKhlon commented on src/test/java/com/bookstore/utils/Messages.java
> +public class Messages {
fixed

2023-02-14 13:08 UTC, MKhlon commented on src/main/java/com/bookstore/model/Booking.java
> +    @JsonFormat(pattern = "HH:mm:ss.SSSSSSSSS")
fixed

2023-02-14 13:08 UTC, MKhlon commented on src/main/java/com/bookstore/controller/BookingController.java
> +                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
thanks, didn't change for now, but will know about it

2023-02-16 17:59 UTC, oleksandr-fomenko approved these changes

2023-02-16 18:45 UTC, merged